# This is a basic workflow to help you get started with Actions

name: CI
   
on: 
  push:
      branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env: 
         code: 54563218515
         account: SimioBlack
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: showing environment variables
        run: |
          echo "Name of  account : ${{env.account}}"
          echo "number of code: ${{env.code}}"
